site_name: Code Constructors
site_url: https://hunterrc.github.io/codeconstructors.github.io/
theme:
  name: material
  features:
    - navigation.top
  logo: images/logo.png

  palette:
  # - scheme: default
  #   toggle:
  #     icon: material/toggle-switch-off-outline
  #     name: Dark Mode
  #   primary: light blue #Header
  #   accent: green #Link hover

  - scheme: slate
    # toggle: 
    #  icon: material/toggle-switch
    #  name: Light Mode
    primary: indigo #Header
    accent: red #Link hover

#  theme:
    


#language: en
markdown_extensions:
  - attr_list
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.tilde
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#  - pymdownx.buttons
  



nav:
  - Home: index.md
  - Projects: 
    - Current Semester: docs/projects/current_semester.md
    - Previous Semesters: docs/projects/previous_semesters.md
  # - Resources: 
  #   - Setting up:
  #   - Information for Beginners:
  #   - Python:
  #   - Colabs:
  #   - GitHub:
  #   - Project Management:


  