site_name: Code Constructors
site_url: https://hunterrc.github.io/codeconstructors.github.io/
theme:
  name: material
  features:
    - navigation.top
    - content.icons
  logo: images/logo.png

  palette:
  # - scheme: default
  #   toggle:
  #     icon: material/toggle-switch-off-outline
  #     name: Dark Mode
  #   primary: light blue #Header
  #   accent: green #Link hover

  - scheme: slate
    # toggle: 
    #  icon: material/toggle-switch
    #  name: Light Mode
    primary: indigo #Header
    accent: light blue #Link hover 

#  theme:
    


#language: en
markdown_extensions:
  - attr_list
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.tilde
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

#  - pymdownx.buttons
  
extra_javascript:
  - https://p.trellocdn.com/embed.min.js


nav:
  - Home: index.md
  - Projects: 
    - Current Semester: projects/current_semester.md
    - Previous Semesters: projects/previous_semesters.md
  - Resources:
    - Setting Up For a Project: resources/setting_up.md

  # - Projects:
  #   - Sample Project: created_projects/sample_project.md
  # - Resources: 
  #   - If you're new start here!:
  #   - Setting up:
  #   - Python:
  #   - Colab:
  #   - GitHub:
  #   - Project Management:



  